version: '3.6'
services:
  jekyll_cli:
    build:
      context: .
      dockerfile: ./Dockerfile_jekyll
    image: teonikolov/jekyll
    volumes:
      - ./docs:/site
  jekyll_serve:
    build:
      context: .
      dockerfile: ./Dockerfile_jekyll-serve
    image: teonikolov/jekyll-serve
    volumes:
      - ./docs:/site
    ports:
      - 4000:4000
      - 4001:4001
    depends_on:
      - jekyll_cli

